#Contents of docker file.
-----------------------------

FROM tomcat:8.5.35-jre10
ADD sample.war /usr/local/tomcat/webapps/
EXPOSE 8080
CMD chmod +x /usr/local/tomcat/bin/catalina.sh
CMD ["catalina.sh", "run"]


#To build docker
 docker build -t new_tomcat .
 docker run -it -p 8787:8080 new_tomcat
